---
title: "shiny ap and uv maps"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(rjson)
library(plotly)
library(flexdashboard)
```

```{r}
tidy_pm_df = read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/ap_uv/pm25.csv")
tidy_oz_df = read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/ap_uv/o3.csv")
tidy_uv_df = read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/ap_uv/edd.csv")
extreme_value = read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/ap_uv/ext_value.csv")
```

```{r}
url1 = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties = rjson::fromJSON(file = url1)
g = list(
  visible = FALSE,
  fitbounds = "locations"
)

map_gen = function(y, s, d){
  mx = mn = 0
  plot_title = ""
  
  if(d == "PM2.5"){
    new_df = rename(tidy_pm_df, value = PM2.5)
    mx = pull(extreme_value, 1)
    mn = pull(extreme_value, 4)
    plot_title = "Average Daily PM 2.5 Level"
  }
  if(d == "O3"){
    new_df = rename(tidy_oz_df, value = O3)
    mx = pull(extreme_value, 2)
    mn = pull(extreme_value, 5)
    plot_title = "Average Daily O3 Level"
  }
  
  if(d == "UV"){
    new_df = rename(tidy_uv_df, value = UV)
    mx = pull(extreme_value, 3)
    mn = pull(extreme_value, 6)
    plot_title = "Average Daily UV Level"
  }
  
  new_df %>% 
    filter(year == y, state == s) %>% 
    select(countyfips, value, hover) %>% 
    plot_geo() %>% 
    add_trace(
      geojson = counties,
      locations = ~ countyfips,
      z = ~ value,
      text = ~ hover,
      
      colorscale = "Viridis",
      
      zmin = mn,
      zmax = mx,
      marker = 
        list(
          line = list(width = 0)
        )
    ) %>% 
    colorbar(title = "") %>%
    layout(
      title = plot_title,
      geo = g
    )
}

all_map_gen = function(y, d){
  mx = mn = 0
  plot_title = ""
  
  if(d == "PM2.5"){
    new_df = rename(tidy_pm_df, value = PM2.5)
    mx = pull(extreme_value, 1)
    mn = pull(extreme_value, 4)
    plot_title = "Average Daily PM 2.5 Level"
  }
  if(d == "O3"){
    new_df = rename(tidy_oz_df, value = O3)
    mx = pull(extreme_value, 2)
    mn = pull(extreme_value, 5)
    plot_title = "Average Daily O3 Level"
  }
  
  if(d == "UV"){
    new_df = rename(tidy_uv_df, value = UV)
    mx = pull(extreme_value, 3)
    mn = pull(extreme_value, 6)
    plot_title = "Average Daily UV Level"
  }
  
  new_df %>% 
    filter(year == y) %>% 
    select(countyfips, value, hover) %>% 
    plot_geo() %>% 
    add_trace(
      geojson = counties,
      locations = ~ countyfips,
      z = ~ value,
      text = ~ hover,
      
      colorscale = "Viridis",
      
      zmin = mn,
      zmax = mx,
      marker = 
        list(
          line = list(width = 0)
        )
    ) %>% 
    colorbar(title = "") %>%
    layout(
      title = plot_title,
      geo = g
    )
}
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
year_choices = c(2001:2016)
# state_choices = c("NY", "OH", "ME", "PA")
# data_choices = c("PM2.5", "O3", "UV")

selectInput(
  "year_choice",
  label = h3("Select Year"),
  choices = year_choices,
  selected = "2001"
)

# selectInput(
#   "state_choice",
#   label = h3("Select State"),
#   choices = state_choices,
#   selected = "NY"
# )

# selectInput(
#   "data_choice",
#   label = h3("Select Data"),
#   choices = data_choices,
#   selected = "PM2.5"
# )
```

Column {data-width=333}
-----------------------------------------------------------------------

### PM2.5 level in NY

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "NY", "PM2.5")
  # all_map_gen(input[["year_choice"]], input[["data_choice"]])
})
```

### PM2.5 level in PA

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "PA", "PM2.5")
})
```

### PM2.5 level in OH

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "OH", "PM2.5")
})
```

Column {data-width=333}
-----------------------------------------------------------------------

### O3 level in NY

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "NY", "O3")
})
```

### O3 level in PA

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "PA", "O3")
})
```

### O3 level in OH

```{r}
renderPlotly({
 map_gen(input[["year_choice"]], "OH", "O3")
})
```

Column {data-width=333}
-----------------------------------------------------------------------

### UV level in NY

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "NY", "UV")
})
```

### UV level in PA

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "PA", "UV")
})
```

### UV level in OH

```{r}
renderPlotly({
  map_gen(input[["year_choice"]], "OH", "UV")
})
```