---
title: "Daily PM2.5 and O3"
author: "Brian Jo Hsuan Lee"
date: "11/23/2021"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
setwd("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/") ## may need to set your own paths to access the rmd and data files
```


```{r}
pm_df = 
  read_csv("../final_raw/Daily_PM2.5_Concentrations_All_County__2001-2016.csv") %>% 
  filter(statefips %in% c(36, 39, 23, 42)) %>% 
  janitor::clean_names() %>% 
  mutate(
    countyfips = statefips*1000 + countyfips,
    day = str_extract(date, "^\\d{2}"),
    day = factor(as.numeric(day)),
    month = str_extract(date, "[A-Z]{3}"),
    month = factor(month)
  ) %>% 
  select(-c(date, statefips)) %>% 
  select(year, countyfips, month, day, everything())
  # nest(pm25 = c(month:pm25_pop_pred))

oz_df = 
  read_csv("../final_raw/Daily_County-Level_Ozone_Concentrations__2001-2016.csv") %>% 
  filter(statefips %in% c(36, 39, 23, 42)) %>% 
  janitor::clean_names() %>% 
  mutate(
    countyfips = as.numeric(statefips)*1000 + countyfips,
    month = factor(month),
    day = factor(day)
  ) %>% 
  select(-statefips) %>% 
  select(year, countyfips, everything())
  # nest(oz = c(month:o3_pop_pred))

```


```{r}
usda_countyfips = read_html("https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697")

countyfips_string =
  usda_countyfips %>%
  html_elements(".data") %>%
  html_text2()

countyfips_matrix = 
  matrix(
    data = unlist(strsplit(countyfips_string, split = "\r "))[-c(1:3)],
    ncol = 3, 
    byrow = TRUE
  )

countyfips_df =
  tibble(
    countyfips = countyfips_matrix[,1],
    county = countyfips_matrix[,2]
  ) %>%
  mutate(
    countyfips = as.numeric(countyfips)
  )
```


```{r}
ap_df = 
  full_join(pm_df, oz_df, by = c("year", "countyfips", "month", "day")) %>% 
  left_join(., countyfips_df, by = "countyfips") %>% 
  mutate(
    statefips = str_extract(countyfips, "^\\d{2}"),
    state = case_when(
      statefips == 36 ~ "NY",
      statefips == 39 ~ "OH",
      statefips == 23 ~ "ME",
      statefips == 42 ~ "PA"
    ),
    state = factor(state),
  ) %>% 
  select(-statefips) %>% 
  select(year, month, day, countyfips, county, state, everything())

ny_ap_df = 
  ap_df %>% 
  filter(state == "NY")

write_csv(ny_ap_df,"./data/daily_ny_ap.csv")

oh_ap_df = 
  ap_df %>% 
  filter(state == "OH")

write_csv(oh_ap_df,"./data/daily_oh_ap.csv")

me_ap_df = 
  ap_df %>% 
  filter(state == "ME")

write_csv(me_ap_df,"./data/daily_me_ap.csv")

pa_ap_df = 
  ap_df %>% 
  filter(state == "PA")

write_csv(pa_ap_df,"./data/daily_pa_ap.csv")
```

```{r}
df = 
  bind_rows(
    read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/daily_ap/daily_ny_ap.csv")
  ) %>% 
  bind_rows(
    read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/daily_ap/daily_oh_ap.csv")
  ) %>% 
  bind_rows(
    read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/daily_ap/daily_me_ap.csv")
  ) %>% 
  bind_rows(
    read_csv("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/p8105-final_project/data/daily_ap/daily_pa_ap.csv")
  )
  
tidy_pm_df =
  df %>% 
  select(-contains('o3')) %>% 
  group_by(year, countyfips, county, state) %>%
  summarize(across(pm25_max_pred:pm25_mean_pred, mean), 
            across(pm25_max_pred:pm25_mean_pred, round, 2)) %>% 
  ungroup() %>% 
  mutate(
    hover = paste(county, '<br>', 
                  "Average Daily Max", pm25_max_pred, '<br>',
                  "Average Daily Median", pm25_med_pred, '<br>'),
    year = factor(year)
  ) %>% 
  rename("PM2.5" = pm25_mean_pred) %>% 
  select(year, countyfips, county, state, PM2.5, hover)

write_csv(tidy_pm_df,"./daily_ap/pm25.csv")

for (i in 2001:2016) {
  year_name_csv = paste("pm25_", i, ".csv", sep = "")
   
  tidy_pm_df %>% 
    filter(year == i) %>% 
    write_csv(paste("./data/daily_ap/", year_name_csv, sep = ""))
}

tidy_oz_df =
  df %>% 
  select(-contains('pm25')) %>% 
  group_by(year, countyfips, county, state) %>%
  summarize(across(o3_max_pred:o3_mean_pred, mean), 
            across(o3_max_pred:o3_mean_pred, round, 2)) %>% 
  ungroup() %>% 
  mutate(
    hover = paste(county, '<br>', 
                  "Average Daily Max", o3_max_pred, '<br>',
                  "Average Daily Median", o3_med_pred),
    year = factor(year)
  ) %>% 
  rename("O3" = o3_mean_pred) %>%
  select(year, countyfips, county, state, O3, hover)

write_csv(tidy_oz_df,"./daily_ap/o3.csv")

for (i in 2001:2016) {
  year_name_csv = paste("o3_", i, ".csv", sep = "")
   
  tidy_oz_df %>% 
    filter(year == i) %>% 
    write_csv(paste("./data/daily_ap/", year_name_csv, sep = ""))
}

extreme_value =
  bind_cols(
    select(tidy_pm_df, PM2.5)
  ) %>% 
  bind_cols(
    select(tidy_oz_df, O3)
  ) %>% 
  summarize(across(c(PM2.5, O3), c(max, min)))

write_csv(extreme_value,"./daily_ap/extreme_value.csv")
```

