---
title: "PM2.5, O3, and UV data merge"
author: "Brian Jo Hsuan Lee"
date: "12/2/2021"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

Data scraping tool
```{r}
usda_countyfips = read_html("https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697")

countyfips_string =
  usda_countyfips %>%
  html_elements(".data") %>%
  html_text2()

countyfips_matrix = 
  matrix(
    data = unlist(strsplit(countyfips_string, split = "\r "))[-c(1:3)],
    ncol = 3, 
    byrow = TRUE
  )

countyfips_df =
  tibble(
    countyfips = countyfips_matrix[,1],
    county = countyfips_matrix[,2]
  ) %>%
  mutate(
    countyfips = as.numeric(countyfips)
  )
```

Load and clean AP data
```{r}
pm_df = 
  read_csv("../final_raw/Daily_PM2.5_Concentrations_All_County__2001-2016.csv") %>% 
  filter(statefips %in% c(36, 39, 23, 42)) %>% 
  janitor::clean_names() %>% 
  mutate(
    countyfips = statefips*1000 + countyfips,
    day = str_extract(date, "^\\d{2}"),
    day = factor(as.numeric(day)),
    month = str_extract(date, "[A-Z]{3}"),
    month = factor(month)
  )

oz_df = 
  read_csv("../final_raw/Daily_County-Level_Ozone_Concentrations__2001-2016.csv") %>% 
  filter(statefips %in% c(36, 39, 23, 42)) %>% 
  janitor::clean_names() %>% 
  mutate(
    countyfips = as.numeric(statefips)*1000 + countyfips,
    month = factor(month),
    day = factor(day)
  )
```

Load and clean UV data
```{r}
uv_df = 
  read_csv("../final_raw/Population-Weighted_Ultraviolet_Irradiance__2004-2015.csv") %>%
  filter(statefips %in% c(36, 39, 23, 42)) %>% 
  mutate(
    day = factor(as.numeric(day)),
    month = factor(month),
    month = recode_factor(month, `1` = "JAN", `2` = "FEB", `3` = "MAR", `4` = "APR",
                          `5` = "MAY", `6` = "JUN", `7` = "JUL", `8` = "AUG",
                          `9` = "SEP", `10` = "OCT", `11` = "NOV", `12` = "DEC", .default = "Other")
  )
```

Join 3 datasets and tidy
```{r}
ap_uv_df = 
  full_join(pm_df, oz_df, by = c("year", "countyfips", "month", "day")) %>% 
  full_join(., uv_df, by = c("year", "countyfips", "month", "day")) %>% 
  left_join(., countyfips_df, by = "countyfips") %>% 
  mutate(
    statefips = str_extract(countyfips, "^\\d{2}"),
    state = case_when(
      statefips == 36 ~ "NY",
      statefips == 39 ~ "OH",
      statefips == 23 ~ "ME",
      statefips == 42 ~ "PA"
    ),
    year = factor(year),
    state = factor(state),
    countyfips = factor(countyfips),
  ) %>% 
  select(-contains("statefips"), -date) %>% 
  select(year, month, day, countyfips, county, state, everything())
```

Export
```{r}
tidy_df =
  ap_uv_df %>% 
  mutate(
    season = case_when(
      month %in% (c("MAR", "APR", "MAY")) ~ "Spring",
      month %in% (c("JUN", "JUL", "AUG")) ~ "Summer",
      month %in% (c("SEP", "OCT", "NOV")) ~ "Fall",
      month %in% (c("DEC", "JAN", "FEB")) ~ "Winter"
    ), 
    season = factor(season),
    season = fct_relevel(season, "Spring", "Summer", "Fall", "Winter")
  ) %>% 
  filter(year %in% c(2005:2015)) %>% 
  group_by(year, countyfips, county, state, season) %>%
  summarize(across(pm25_max_pred:i380, median, na.rm = TRUE), 
            across(pm25_max_pred:i380, round, 2)) %>% 
  ungroup()

saveRDS(tidy_df,"ap/apuv_map/apuv.RDS")

extreme_value =
  bind_cols(
    bind_cols(
      select(tidy_pm_df, PM2.5)
    ) %>% 
    bind_cols(
      select(tidy_oz_df, O3)
    ) %>% 
    bind_cols(
      select(tidy_uv_df, UV)
    ) %>%
    summarize(across(c(PM2.5:UV), max, na.rm =TRUE))
  ) %>% 
  bind_cols(
    bind_cols(
      select(tidy_pm_df, PM2.5)
    ) %>% 
    bind_cols(
      select(tidy_oz_df, O3)
    ) %>% 
    bind_cols(
      select(tidy_uv_df, UV)
    ) %>% 
    summarize(across(c(PM2.5:UV), min, na.rm =TRUE))
  )

saveRDS(extreme_value,"ap/apuv_map/ext_val.RDS")
```

